using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class BuildingGenerator : MonoBehaviour
{
    // Class for generating buildings based on the road network generated by the RoadNetwork class
    // Generate some houses ya bish
    public void GenerateTestHouse()
    {
        OrientedPoint testPoint = GameObject.Find("Main Road").GetComponent<Road>().path.First();

        GameObject house = GameObject.CreatePrimitive(PrimitiveType.Cube);
        house.name = "house";
        house.transform.parent = this.transform;
        house.transform.rotation = testPoint.rotation;
        house.transform.position = testPoint.position + testPoint.rotation * Vector3.left * 20;

    }
}
